name: Farming
version: '${project.version}'
main: com.undercover.farming.Farming
api-version: 1.18
authors: [ Undercover#9773 ]
description: Adds a command to help u farm
commands:
  plant:
    permission: farming.plant
    description: Plants whatever item you are holding in your hand in an expanding circle starting where you are looking at an optional given speed (0 is instant, and 32 is slowest)
    usage: "Usage: /plant [0-32]"

